### PR TITLE
Fix issue splitting lines by platform

### LINKED ISSUE #15: Allowlist/Denylist not working in some OS system
### Description of the bug

The allowlist/denylist you use this plugin use `explode("\n", $list)` syntax.
But as you know, this code does not work in some OS system, because the newline is different by systems.
Can you change this logic into more safe function?

```
      $allowlist = preg_split( "/\r\n|\n|\r/", $allowlist );

```

### Steps To Reproduce

1. Open REST API Guard Settings page on Mac OS
2. Enter more than 2 endpoints in "Anonymous Request Allowlist"
3. Call the API request
4. It returns 401 error

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by srtfisher**
Fixes #15

### CODE REVIEW

File: plugin.php [hunk 1]
```diff
@@ -127,10 +130,15 @@ function should_prevent_anonymous_access( WP_REST_Server $server, WP_REST_Reques
 
 	if ( ! empty( $denylist ) ) {
 		if ( ! is_array( $denylist ) ) {
-			$denylist = explode( "\n", $denylist );
+			$denylist = preg_split( '/\r\n|\r|\n/', $denylist );
 		}
 
 		foreach ( $denylist as $denylist_endpoint ) {
+			// Strip off /wp-json from the beginning of the endpoint if it was included.
+			if ( 0 === strpos( $denylist_endpoint, '/wp-json' ) ) {
```
Comment (attackant) [inline plugin.php:138]:
```suggestion
			if ( str_starts_with($denylist_endpoint, '/wp-json') ) {
```

File: plugin.php [hunk 2]
```diff
@@ -104,10 +102,15 @@ function should_prevent_anonymous_access( WP_REST_Server $server, WP_REST_Reques
 
 	if ( ! empty( $allowlist ) ) {
 		if ( ! is_array( $allowlist ) ) {
-			$allowlist = explode( "\n", $allowlist );
+			$allowlist = preg_split( '/\r\n|\r|\n/', $allowlist );
 		}
 
 		foreach ( $allowlist as $allowlist_endpoint ) {
+			// Strip off /wp-json from the beginning of the endpoint if it was included.
+			if ( 0 === strpos( $allowlist_endpoint, '/wp-json' ) ) {
```
Comment (attackant) [inline plugin.php:110]:
```suggestion
			if ( str_contains( $allowlist_endpoint, '/wp-json' ) ) {
```

**Review by attackant — APPROVED** [review]
👍🏼
